language: java
java:
  - 1.8
jdk:
  - oraclejdk8
 
addons:
  - sonarqube: true
  - postgresql: "9.4"
  
before_install:
  - sudo apt-get purge postgresql-9.1 postgresql-9.2 postgresql-9.3
  - sudo /etc/init.d/postgresql stop
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.4" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get install postgresql-9.4
  - sudo service postgresql-9.4 start

before_script:
 - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
 - cp config/database.yml.travis config/database.yml
 - psql -c 'create database integragenda;' -U postgres
 - psql -U postgres -d integragenda < dump
 
script:
  - mvn clean install sonar:sonar -Dmaven.test.skip=false
  
notifications:
  slack: integragenda:D6kydUY1wzAKAbdLPmre18wr
