language: java
java:
  - 1.8
jdk:
  - oraclejdk8
 
addons:
  - sonarqube: true
  - postgresql: "9.4"
  
before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y remove --purge postgresql-9.1
  - sudo apt-get -y remove --purge postgresql-9.2
  - sudo apt-get -y remove --purge postgresql-9.3
  - sudo apt-get update
  - sudo apt-get install postgresql-9.4
  - sudo service postgresql start 9.4 

before_script:
 - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
 - cp config/database.yml.travis config/database.yml
 - psql -c 'create database integragenda;' -U postgres
 - psql -U postgres -d integragenda < dump3
 
script:
  - mvn clean install sonar:sonar -Dmaven.test.skip=false
  
notifications:
  slack: integragenda:D6kydUY1wzAKAbdLPmre18wr
