language: java
java:
  - 1.8
jdk:
  - oraclejdk8
  
services:
  - postgresql

addons:
  - sonarqube: true
  - postgresql: "9.4"

before_script:
 - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
 - cp config/database.travis.yml config/database.yml
 - psql -c 'create database integragenda;' -U postgres
 - psql -U postgres -d integragenda < dump

script:
  - mvn clean install sonar:sonar -Dmaven.test.skip=false
  
notifications:
  slack: integragenda:D6kydUY1wzAKAbdLPmre18wr
